name: Post random job on Slack

on:
  push:
    branches:
      - main

jobs:
  post_job_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Get random job
        run: |
          job_data=$(curl -s https://shesharpnl.github.io/hackathon-2023.sourcestack-data/assets/junior-nl.json | jq '.data | .[]' | shuf -n 1)
          echo "::set-output name=random_job::$job_data"
        id: get_job
      - name: Post to Slack
        if: ${{ steps.get_job.outputs.random_job != '' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          random_job="${{ steps.get_job.outputs.random_job }}"
          payload="{\"attachments\": [{\"color\": \"#00FF00\",\"blocks\": [{\"type\": \"header\",\"text\": {\"type\": \"plain_text\",\"text\": \"New job alert! :tada:\"}},{\"type\": \"section\",\"text\": {\"type\": \"mrkdwn\",\"text\": \"A new job posting has just been added to our website. Check it out!\"}}]}]}"
          curl -X POST -H "Content-type: application/json" --data-raw "${payload}" "${SLACK_WEBHOOK_URL}"
